name: 🐞 反馈一个Bug
description: 通过模板反馈bug
title: "[BUG Report] 请输入一个标题"
labels: ["bug: need confirm"]
body:
- type: markdown
  attributes:
    value: |
      在此之前，请注意：

      - 如果不是反馈 Bug，请到 [Discussions 讨论区](https://github.com/Liberty-liu/Everright-filter/discussions) 发帖。
      - 如果可以的话，请提供一个尽可能简单的 [codesandbox](https://codesandbox.io) 或 GitHub 仓库链接。
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: macOS 13.4.1
        - **Node**: 16.16.0
        - **pnpm**: 7.9.5
        - **vue**: 3.2.47
        - **element-plus**: 2.3.1
    value: |
        - OS:
        - Node:
        - pnpm:
        - vue:
        - element-plus:
    render: markdown
  validations:
    required: true
- type: input
  id: browsers
  attributes:
    label: 设备/浏览器
    description: 在哪些设备/浏览器上能重现这个问题？
  validations:
    required: true
- type: textarea
  attributes:
    label: 描述一下你的问题
    placeholder: 如下拉框无法打开
  validations:
    required: true
- type: textarea
  attributes:
    label: 重现步骤
    description: 提供一个可以复现的操作步骤，以便能够重现问题。
    placeholder: |
        比如：
        1. 点击按钮
        2. 无法删除条件
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
