name: 🐞 Bug Report
description: File a bug/issue
title: "[BUG Report] Title"
labels: ["bug: need confirm"]
body:
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: macOS 13.4.1
        - **Node**: 16.16.0
        - **pnpm**: 7.9.5
        - **vue**: 3.2.47
        - **element-plus**: 2.3.1
    value: |
        - OS:
        - Node:
        - pnpm:
        - vue:
        - element-plus:
    render: markdown
  validations:
    required: true
- type: input
  id: browsers
  attributes:
    label: Device/Browser
    description: On which devices/browsers can the problem be reproduced?
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the Bug
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
        e.g.
        1. Click button
        2. Can't delete condition
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
